server:
  port: 9527
spring:
  redis:
    host: 10.6.80.35
    port: 6379
    # 密码 没有则可以不填
    password: 123456
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0

# 配置域名，如果没有配，则默认是本地ip
common:
   domain: http://127.0.0.1:9527

# 缓存配置
cache:
  # Redis缓存key前缀，默认为 shortcut_
  prefix: shortcut_